const mongoose = require('mongoose');

const libraryRequestSchema = mongoose.Schema(
  {
    student: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'User',
      required: true,
    },
    // Book details (snapshots from the external API)
    bookTitle: { type: String, required: true },
    bookAuthor: { type: String },
    bookImage: { type: String },
    
    // Request Token generated by frontend or backend ID can be used
    token: { type: String }, 

    status: {
      type: String,
      enum: ['Pending', 'Approved', 'Rejected', 'Returned'],
      default: 'Pending',
    },
    
    // Administrative fields
    adminMessage: { type: String, default: '' },
    
    // Dates
    requestDate: { type: Date, default: Date.now },
    issueDate: { type: Date }, // Set when Admin approves
    dueDate: { type: Date },   // Set to +14 days after approval
    returnDate: { type: Date }, // Set when returned
  },
  { timestamps: true }
);

module.exports = mongoose.model('LibraryRequest', libraryRequestSchema);